### ISSUE TITLE
Segfault with latest commit (Commit Function)

### ISSUE THREAD

**Issue by nmcglohon** [carothersc/ROSS#101]
When running template-model on commit d3bdc077a0c4d1481dc06c4b4d4f1eb8e4e6fbf6 it results in a segfault. I have noticed this on two Mac machines and experience the same error when running my own model which is based on template-model and phold. 

That being said, Phold still works.

Rolling back to RIO v2 commit bbfe137777e4eec3a6ef7a25e1b8a0778e902815 resolves the error.

**Comment by gonsie** [comment]
It looks like I forgot to add a commit function to the template model. If you make the change I'll accept a pull request.

**Comment by nmcglohon** [comment]
Ah yeah - I had just now realized that the commit_f was missing, my bad. I'll try that out.
