### ISSUE TITLE
line numbers on all code in blog

### ISSUE THREAD

**Issue by gonsie** [carothersc/ROSS#105]
There is something weird happening with code on the blog. Even inline code (code surrounded by back ticks \`) is placed into a table with line numbers.

Yes we want line numbers, but only on larger code blocks.

**Comment by gonsie** [comment]
hey that actually worked!
https://github.com/carothersc/ROSS/commit/ef11c21a78cf199d844755c38f20fe0ecc1cbb5a

**Comment by caitlinross** [comment]
Thanks!  I was wondering what happened, but was going to try to figure it out later.
