### ISSUE TITLE
Running gvt-7o`clock Algorithm for GVT Computation 

### ISSUE THREAD

**Issue by aliardaeker** [carothersc/ROSS#118]
Hello,

I was trying to use gvt-7o`clock instead of gvt-mpi_allreduce for gvt computation but when I run the simulator it doesn`t know the type tw_volatile and it gives me undefined reference errors for tw_net_send_lvt() and tw_net_gvt_compute() functions.

These functions are decleared in ross-network.h but not defined in network-mpi.c as they should be. Could any one have a idea about the problem?

Thank you.

**Comment by caitlinross** [comment]
Those functions aren't declared because the 7 o'clock GVT isn't currently being used in ROSS (hence the '.old' on the end of the file name in the repo).  `gvt/mpi_allreduce.c` provides the GVT functionality now.

**Comment by aliardaeker** [comment]
Ohh, ok I got it. Thank you.
