### ISSUE TITLE
ROSS C code should compile cleanly in a C++ context

### ISSUE THREAD

**Issue by laprej** [carothersc/ROSS#31]
For some reason, this isn't working right now.

**Comment by carothersc** [comment]
What specifically is breaking ??

It's probably a CMake / Config issue ??

t

On Thu, Feb 19, 2015 at 1:54 PM, Justin M. LaPre <notifications@github.com>
wrote:

>  For some reason, this isn't working right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carothersc/ROSS/issues/31>.
>



-- 
----------------------------------------------------------------------------------------------
Christopher D. Carothers

Director, Center for Computational Innovations
Professor, Department of Computer Science
Rensselaer Polytechnic Institute
110 8th Street
Troy, New York 12180-3590

e-mail: chrisc@cs.rpi.edu
web page: www.cs.rpi.edu/~chrisc
phone: (518) 276-2930
fax: (518) 276-4033
----------------------------------------------------------------------------------------------

**Comment by laprej** [comment]
Mainly a lot of void * issues which C++ has a problem with.

**Comment by gonsie** [comment]
Is there a way we can integrate this into the continuous integration tests?
