### ISSUE TITLE
Website with Details

### ISSUE THREAD

**Issue by gonsie** [carothersc/ROSS#45]
In order to grow the ROSS user base, we need a better website/landing page for people interested in our software. It should contain links to publications, both for ROSS core and various ROSS models. We should also keep track of the records that ROSS holds and a history of performance on various machines.

**Comment by carothersc** [comment]
Thanks Elsa -- what do you think of the Charm++ website ? They seems to
have what you're talking about ...

thanks!,
Chris

On Wed, Jun 24, 2015 at 10:18 AM, Elsa Gonsiorowski <
notifications@github.com> wrote:

>  In order to grow the ROSS user base, we need a better website/landing
> page for people interested in our software. It should contain links to
> publications, both for ROSS core and various ROSS models. We should also
> keep track of the records that ROSS holds and a history of performance on
> various machines.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carothersc/ROSS/issues/45>.
>



-- 
----------------------------------------------------------------------------------------------
Christopher D. Carothers

Director, Center for Computational Innovations
Professor, Department of Computer Science
Rensselaer Polytechnic Institute
110 8th Street
Troy, New York 12180-3590

e-mail: chrisc@cs.rpi.edu
web page: www.cs.rpi.edu/~chrisc <http://www.cs.rpi.edu/%7Echrisc>
phone: (518) 276-2930
fax: (518) 276-4033
----------------------------------------------------------------------------------------------

**Comment by gonsie** [comment]
The charm site is fine... I personally think the CODES website looks nicer.

**Comment by gonsie** [comment]
While still incomplete, a new website has been created. Checkout http://carothersc.github.io/ROSS/.
