### ISSUE TITLE
Requirements Documentation

### ISSUE THREAD

**Issue by gonsie** [carothersc/ROSS#61]
We should document which packages are required for ROSS. The ones that immediately come to mind are:

- CMake
- MPI (mpich recommended)
- anything else?

**Comment by laprej** [comment]
I don't think anything else is required...  I pulled the lz4.[ch] files from their distribution but they have their own BSD license information at the top so I don't believe that causes any problems.  We did recently boost the minimum CMake version to 2.8 but that's still pretty old so I don't think _that_ should cause grief for anyone.  Aside from those issues, nothing comes to mind.

**Comment by gonsie** [comment]
closed by 5ed2ab0bf4eb1af1d18378ac9dec97b021dc4e6a
