### ISSUE TITLE
RNG Seeding

### ISSUE THREAD

**Issue by gonsie** [carothersc/ROSS#62]
We need to clarify the documentation and remove any deprecated code (global variable g_tw_rng_seed and the 3rd argument it tw_define_lps).

@JohnPJenkins remembered this quote from @carothersc while discussing 45665b48a649b136f173a47916ab231c6cd92a07:

> I think we stopped using that parameter since we did not want users picking 
> their own seeds as some seeds are better than others and some are just bad.
> 
> So, a little primer here on RNGs. RNGs in fact have only one (hopefully) very, very
> long stream of random numbers. CLCG4 uses 4, 32bit values or 128 bits. 
> This generator has a period of 2^121 implying that ~2^7 values are missing
> from the generator.This is fine. 
> 
> So, you can image a circle with 2^121 tiny point going around the circumference
> where each point would represent a random value. Eventually, if you called
> the generator 2^121 times, you would have made it around the circle.
> 
> A very nice property of CLCG4 is that you can jump (or virtually teleport) ahead
> in that single stream of random numbers. We call it "seed jumping". ROSS
> starts from the default seed and jumps 2^70 calls ahead in the stream for each
> LP. That is, each LP's starting point in the random stream circle is 2^72 calls
> apart.  So, in theory, we could support simulation with unto 2^49 LPs and each
> LP have it's on part of the random stream, uncorrelated from other parts.
> 
> Now, to change seed sets, what you really want to do is change where each LP
> starts on the random stream circle. 
> 
> You can do this by increasing g_tw_nRNGs_per_lp. So, suppose you use 4.
> That will give each LP 4 distinct RNG seed sets that start again 2^72 calls
> apart. 
> 
> In your model code, you just change which seed set you wish to us -- 0, 1, 2, 3
> e.g., lp->rng[0] or lp->rng[1], lp->rng[2] or lp->rng[3].
> 
> By default in ROSS, when you use lp->rng your really saying &(lp->rng[0]).
> 
> The downside of this approach is you're potentially wasting some memory by
> have these 4 seed sets around and the cost to compute them but it's a very
> low cost all around unless you have a model with billions of LPs.
> 
> If that is the case, you would have to directly jump or shift seeds an LP uses
> by directly invoking the seed jumping routine w/i the RNG with the LPs
> init event.  
> 
> e.g., call, tw_rand_initial_seed(&lp->rng[i], lp->gid + offset);
> where offset would be the number of 2^70 jumps you want to make beyond the
> LP's global id.

**Comment by laprej** [comment]
OK, so I think ad0118e0b638d6bfa9cb5827c1b41e5d628d85f3 closes this issue...  Also see 8b7b3951a7a831e4781a5468ee62af5d9eb5ce7e for more details on re-seeding RNGs.
