### ISSUE TITLE
Round Robin Mapping is Broken

### ISSUE THREAD

**Issue by gonsie** [carothersc/ROSS#69]
LP IDs on each Rank always start at 0. Not good.

**Comment by carothersc** [comment]
This was done so the Local LP id is used as an index in the local LP array.

What is broken about Round Robin mapping ?

Thanks,
Chris

----------------------------------------------------------------------------------------------
Christopher D. Carothers

Director, Center for Computational Innovations
Professor, Department of Computer Science
Rensselaer Polytechnic Institute
110 8th Street
Troy, New York 12180-3590

e-mail: chris.carothers@gmail.com
web page: www.cs.rpi.edu/~chrisc<http://www.cs.rpi.edu/%7Echrisc>
phone: (518) 276-2930<tel:%28518%29%20276-2930>
fax: (518) 276-4033<tel:%28518%29%20276-4033>
----------------------------------------------------------------------------------------------
________________________________

**Comment by gonsie** [comment]
Sorry, I meant to say that LP GIDs always start at 0. Each MPI Rank has an LP 0.
