### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by gonsie** [carothersc/ROSS#77]
Should we document how people can contribute to ROSS? I think it would go a long to making people feel more comfortable diving into the code.

https://github.com/blog/1184-contributing-guidelines

**Comment by carothersc** [comment]
Yes - sounds good to me. Thanks for suggesting it..
Chris

----------------------------------------------------------------------------------------------
Christopher D. Carothers

Director, Center for Computational Innovations
Professor, Department of Computer Science
Rensselaer Polytechnic Institute
110 8th Street
Troy, New York 12180-3590

e-mail: chris.carothers@gmail.com
web page: www.cs.rpi.edu/~chrisc<http://www.cs.rpi.edu/%7Echrisc>
phone: (518) 276-2930<tel:%28518%29%20276-2930>
fax: (518) 276-4033<tel:%28518%29%20276-4033>
----------------------------------------------------------------------------------------------
________________________________
