### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by gonsie** [carothersc/ROSS#96]
@laprej What is the difference between codecov and coveralls?

**Comment by laprej** [comment]
Coveralls has some weird metrics so I would be in favor of dumping that one and keeping Codecov.  The trick is I'm using the code originally from Coveralls to drive both of them.  I could simply remove permissions from Coveralls and that would cut down on the emails.

**Comment by gonsie** [comment]
Do you want to write a blog post about it? :)

**Comment by laprej** [comment]
Not particularly :)  I find Coveralls coverage metrics to be slightly confusing.  That's why we link to Codecov -- it's much more in line with what I would expect from a coverage service.

**Comment by gonsie** [comment]
Yeah, getting rid of coveralls would clarify things. Though, interestingly, the RIO PR #95 passed codecov but not coveralls (it really should not pass since I haven't written a test for it).

**Comment by laprej** [comment]
See #97 for a branch to take care of this noise.

**Comment by gonsie** [comment]
closed by #100 and/or #97 ?
