### ISSUE TITLE
Why is g_tw_clock_rate of type tw_stime (double)????????

### ISSUE THREAD

**Issue by gonsie** [carothersc/ROSS#98]
Wouldn't tw_clock or unsigned long long make more sense? 

On a somewhat related note, has the optimistic realtime scheduler been tested on the BGQ?

**Comment by markplagge** [comment]
When doing work on NeMo, I ran optimistic realtime for performance testing on the BlueGene/Q. I did not include the results in my PADS paper, but they were promising. I'm anticipating using it with the next revision of NeMo.

**Comment by gonsie** [comment]
After talking with Chris, g_tw_clock_rate should just be an unsigned long long. No need for it to be a tw_stime/double. This should be an easy fix.
